num=[10,20,30,40,50]
print(num,type(num))
print("accessing the list elements using +ve indexing :")
print(num[0])
print(num[1])
print(num[2])
print(num[3])
print(num[4])
print("accessing the list elements using -ve indexing :")
print(num[-5])
print(num[-4])
print(num[-3])
print(num[-2])
print(num[-1])
